import pptxgen from "pptxgenjs";
import { PresentationData, TemplateId } from "../types";

// Define styles for different templates
const TEMPLATES = {
  classic: {
    background: "FFFFFF",
    color: "000000",
    accent: "2563EB", // Blue
    accentText: "FFFFFF",
    font: "Arial",
    barColor: "2563EB"
  },
  modern: {
    background: "F8FAFC", // Slate-50
    color: "334155", // Slate-700
    accent: "0F172A", // Slate-900
    accentText: "FFFFFF",
    font: "Verdana",
    barColor: "0F172A"
  },
  dark: {
    background: "111827", // Gray-900
    color: "E5E7EB", // Gray-200
    accent: "6366F1", // Indigo-500
    accentText: "FFFFFF",
    font: "Calibri",
    barColor: "6366F1"
  },
  corporate: {
    background: "FFFFFF",
    color: "1F2937",
    accent: "059669", // Emerald-600
    accentText: "FFFFFF",
    font: "Georgia",
    barColor: "059669"
  }
};

export const generatePptFile = async (data: PresentationData) => {
  const pres = new pptxgen();
  const templateId = data.template || 'classic';
  const theme = TEMPLATES[templateId];

  // Set Metadata
  pres.title = data.title;
  pres.subject = "Research Summary";
  pres.layout = "LAYOUT_16x9";

  // Define Master Slide Styles
  pres.defineSlideMaster({
    title: "MASTER_SLIDE",
    background: { color: theme.background },
    objects: [
      {
        rect: { x: 0, y: 0, w: "100%", h: 0.8, fill: { color: theme.barColor } },
      },
      {
        text: {
          text: data.title,
          options: { x: 0.5, y: 0.15, w: "80%", fontSize: 14, color: theme.accentText, align: "left", fontFace: theme.font },
        },
      },
      {
        rect: { x: 0, y: 6.8, w: "100%", h: 0.7, fill: { color: theme.barColor } },
      },
      {
        text: {
          text: "Generated by Research2PPT",
          options: { x: 0.5, y: 7.0, w: "40%", fontSize: 10, color: theme.accentText, fontFace: theme.font },
        },
      },
      {
        slideNumber: { x: "92%", y: "90%", fontSize: 10, color: theme.accentText, fontFace: theme.font }
      }
    ],
  });

  // 1. Title Slide
  const titleSlide = pres.addSlide();
  titleSlide.background = { color: theme.background };

  // Title Slide Layout
  if (data.titleImage) {
    // Layout with Image: Left Text, Right Image
    titleSlide.addText(data.title, {
      x: 0.5, y: 1.5, w: "45%", fontSize: 40, color: theme.color, bold: true, align: "left", fontFace: theme.font
    });
    if (data.subtitle) {
      titleSlide.addText(data.subtitle, {
        x: 0.5, y: 3.5, w: "45%", fontSize: 20, color: theme.accent, align: "left", fontFace: theme.font
      });
    }
    titleSlide.addImage({
      data: data.titleImage,
      x: "55%", y: 1.0, w: "40%", h: 5.0,
      sizing: { type: "contain", w: "40%", h: 5.0 }
    });
  } else {
    // Standard Centered Layout
    // Add a decorative splash if no image
    titleSlide.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: "100%", h: "100%", fill: { color: theme.accent, transparency: 90 } });
    
    titleSlide.addText(data.title, {
      x: 1, y: 2.0, w: "80%", fontSize: 44, color: theme.color, bold: true, align: "center", fontFace: theme.font
    });
    if (data.subtitle) {
      titleSlide.addText(data.subtitle, {
        x: 1, y: 4, w: "80%", fontSize: 24, color: theme.accent, align: "center", fontFace: theme.font
      });
    }
  }

  // 2. Content Slides
  data.slides.forEach((slideData) => {
    const slide = pres.addSlide({ masterName: "MASTER_SLIDE" });

    // Slide Title
    slide.addText(slideData.title, {
      x: 0.5, y: 1.0, w: "90%", fontSize: 32, color: theme.color, bold: true, fontFace: theme.font
    });

    const hasImage = !!slideData.image;
    
    // Bullet Points
    const bullets = slideData.bulletPoints.map(point => ({
      text: point,
      options: { fontSize: 16, color: theme.color, breakLine: true, indentLevel: 0, bullet: true }
    }));

    if (hasImage && slideData.image) {
      // Split Layout: Text Left, Image Right
      slide.addText(bullets, {
        x: 0.5, y: 2.0, w: "55%", h: 4.5, lineSpacing: 28, fontFace: theme.font
      });
      
      slide.addImage({
        data: slideData.image,
        x: "62%", y: 2.0, w: "33%", h: 4.0,
        sizing: { type: "contain", w: "33%", h: 4.0 }
      });
    } else {
      // Full Width Layout
      slide.addText(bullets, {
        x: 0.5, y: 2.0, w: "90%", h: 4.5, lineSpacing: 32, fontFace: theme.font
      });
    }

    // Speaker Notes
    slide.addNotes(slideData.speakerNotes);
  });

  // Save the file
  const fileName = `${data.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pptx`;
  await pres.writeFile({ fileName });
};